spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8989/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9000